# Generated by Django 6.0.3 on 2026-04-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("POTHOLE", "Pothole"),
                    ("GARBAGE", "Garbage Overflow"),
                    ("STREETLIGHT", "Streetlight Failure"),
                    ("WATER_LEAK", "Water Leakage"),
                    ("TRAFFIC", "Traffic Issue"),
                    ("MISC", "Miscellaneous"),
                ],
                max_length=20,
            ),
        ),
    ]
