# Generated by Django 6.0.3 on 2026-04-05 11:23

from django.db import migrations, models


def migrate_closed_to_resolved(apps, schema_editor):
    """Convert any existing CLOSED incidents/status-updates to RESOLVED."""
    Incident = apps.get_model('incidents', 'Incident')
    StatusUpdate = apps.get_model('incidents', 'StatusUpdate')
    Incident.objects.filter(status='CLOSED').update(status='RESOLVED')
    StatusUpdate.objects.filter(status='CLOSED').update(status='RESOLVED')


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_add_misc_incident_type"),
    ]

    operations = [
        # 1. Data migration first — move CLOSED rows to RESOLVED before removing the choice
        migrations.RunPython(migrate_closed_to_resolved, migrations.RunPython.noop),

        # 2. Update model choices
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("ESCALATED", "Escalated"),
                    ("RESOLVED", "Resolved"),
                ],
                default="SUBMITTED",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="statusupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("ESCALATED", "Escalated"),
                    ("RESOLVED", "Resolved"),
                ],
                max_length=15,
            ),
        ),
    ]
